# AUTO-GENERATED -- DO NOT EDIT.
# Generated from the live Human Crash Baselines OpenAPI schema by
# scripts/regenerate_models.py.
# Re-run that script after any API contract change.

# generated by datamodel-codegen:
#   filename:  humanbaselines_openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class CiMethod(Enum):
    fay_feuer = 'fay_feuer'
    empirical_bayes = 'empirical_bayes'


class ComputeBatchItem(BaseModel):
    county: str = Field('travis', title='County')
    selections: dict[str, Any] | None = Field(None, title='Selections')
    cell_filter: list[str] | None = Field(None, title='Cell Filter')


class ComputeBatchRequest(BaseModel):
    items: list[ComputeBatchItem] | None = Field(None, title='Items')
    summary_only: bool = Field(True, title='Summary Only')


class ComputeRequest(BaseModel):
    county: str = Field('travis', title='County')
    selections: dict[str, Any] | None = Field(None, title='Selections')
    cell_filter: list[str] | None = Field(None, title='Cell Filter')
    summary_only: bool = Field(False, title='Summary Only')


class SegmentId(RootModel[tuple[str, int]]):
    root: tuple[str, int] = Field(..., max_length=2, min_length=2)


class ComputeRouteRequest(BaseModel):
    county: str = Field('travis', title='County')
    segment_ids: list[SegmentId] = Field(..., title='Segment Ids')
    selections: dict[str, Any] | None = Field(None, title='Selections')


class DenominatorVmt(Enum):
    calibrated = 'calibrated'
    hpms = 'hpms'


class DepotComputeResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )


class DepotPin(BaseModel):
    lat: float = Field(..., title='Lat')
    lon: float = Field(..., title='Lon')


class DriverImpairment(Enum):
    any = 'any'
    exclude_impaired = 'exclude_impaired'
    impaired_only = 'impaired_only'


class FilterOption(BaseModel):
    id: str = Field(..., title='Id')
    label: str = Field(..., title='Label')


class OperatorWeight(RootModel[float]):
    root: float = Field(..., gt=0.0, title='Operator Weight')


class InTransport(Enum):
    in_transport = 'in_transport'
    include_all = 'include_all'


class LightFilter(Enum):
    any = 'any'
    daylight = 'daylight'
    dawn_dusk = 'dawn_dusk'
    dark = 'dark'


class MultiplierVmt(Enum):
    calibrated = 'calibrated'
    hpms = 'hpms'


class OperatorWeighting(Enum):
    county_wide = 'county_wide'
    robotaxi = 'robotaxi'


class Outcome(Enum):
    police_reported = 'police_reported'
    observed_any_injury = 'observed_any_injury'
    airbag = 'airbag'
    ego_airbag = 'ego_airbag'
    ka = 'ka'
    fatal = 'fatal'


class PerCellResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    s2_cell: str = Field(..., title='S2 Cell')
    count: float = Field(..., title='Count')
    vmt: float = Field(..., title='Vmt')
    mult_contrib: float = Field(0.0, title='Mult Contrib')


class PerSegmentResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    route: str = Field(..., title='Route')
    milepost: int = Field(..., title='Milepost')
    count: float = Field(..., title='Count')
    vmt: float = Field(..., title='Vmt')
    length_mi: float = Field(..., title='Length Mi')


class RegionInfo(BaseModel):
    county: str = Field(..., title='County')
    modes: list[str] = Field(..., title='Modes')


class RegionsResponse(BaseModel):
    regions: list[RegionInfo] = Field(..., title='Regions')
    default_county: str = Field('travis', title='Default County')


class RoadGroup(Enum):
    interstate = 'interstate'
    other_freeway = 'other_freeway'
    arterial = 'arterial'
    collector_local = 'collector_local'


class RouteComputeResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    N: float = Field(..., title='N')
    trip_miles: float = Field(..., title='Trip Miles')
    rate: float = Field(..., title='Rate')
    rate_low: float | None = Field(None, title='Rate Low')
    rate_high: float | None = Field(None, title='Rate High')
    variance: float | None = Field(None, title='Variance')
    segments: list[PerSegmentResult] | None = Field(None, title='Segments')
    exposure_sources: list[str] | None = Field(None, title='Exposure Sources')
    crash_sources: list[str] | None = Field(None, title='Crash Sources')


class Tier3Mode(Enum):
    marginal = 'marginal'
    none = 'none'
    all = 'all'


class UnderReporting(Enum):
    none = 'none'
    adjusted = 'adjusted'


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class VehicleClass(Enum):
    cars = 'cars'
    light_trucks = 'light_trucks'
    heavy_trucks = 'heavy_trucks'
    motorcycles = 'motorcycles'
    buses = 'buses'
    other = 'other'


class WeatherFilter(Enum):
    any = 'any'
    dry = 'dry'
    rain = 'rain'
    fog = 'fog'
    winter_storm = 'winter_storm'


class ComputeDepotRouteRequest(BaseModel):
    county: str = Field('travis', title='County')
    depot_a: DepotPin
    depot_b: DepotPin
    selections: dict[str, Any] | None = Field(None, title='Selections')


class ComputeResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    N: float = Field(..., title='N')
    D_miles: float = Field(..., title='D Miles')
    D_billions: float = Field(..., title='D Billions')
    rate: float = Field(..., title='Rate')
    rate_low: float | None = Field(None, title='Rate Low')
    rate_high: float | None = Field(None, title='Rate High')
    rate_non_dyn: float = Field(..., title='Rate Non Dyn')
    rate_dyn: float | None = Field(None, title='Rate Dyn')
    multiplier: float | None = Field(None, title='Multiplier')
    cells: list[PerCellResult] | None = Field(None, title='Cells')


class DepotSelections(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Outcome = 'police_reported'
    severity: int = Field(1, ge=1, le=7, title='Severity')
    ego_vehicle: list[VehicleClass] | VehicleClass = Field(
        ['combination'], title='Ego Vehicle'
    )
    unresolved_nfs: Tier3Mode = 'marginal'
    in_transport: InTransport = 'in_transport'
    weather: list[WeatherFilter] | WeatherFilter = Field(
        ['dry', 'rain', 'fog'], title='Weather'
    )
    light_condition: list[LightFilter] | LightFilter = Field(
        'any', title='Light Condition'
    )
    driver_impairment: DriverImpairment = 'any'
    under_reporting: UnderReporting = 'none'
    ci_method: CiMethod = 'empirical_bayes'


class FilterDef(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str = Field(..., title='Id')
    label: str = Field(..., title='Label')
    affects: str = Field(..., title='Affects')
    multiselect: bool = Field(..., title='Multiselect')
    description: str = Field(..., title='Description')
    options: list[FilterOption] = Field(..., title='Options')
    default: Any | None = Field(None, title='Default')


class FiltersResponse(BaseModel):
    modes: dict[str, list[FilterDef]] = Field(..., title='Modes')


class GeofenceSelections(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Outcome = 'police_reported'
    severity: int = Field(1, ge=1, le=7, title='Severity')
    ego_vehicle: list[VehicleClass] | VehicleClass = Field(
        ['cars', 'light_trucks'], title='Ego Vehicle'
    )
    unresolved_nfs: Tier3Mode = 'marginal'
    in_transport: InTransport = 'in_transport'
    road_type: list[RoadGroup] | RoadGroup = Field(
        ['arterial', 'collector_local'], title='Road Type'
    )
    operator_weighting: OperatorWeighting = 'county_wide'
    multiplier_vmt: MultiplierVmt = 'calibrated'
    operator_weight: OperatorWeight | None = Field(None, title='Operator Weight')
    denominator_vmt: DenominatorVmt = 'calibrated'
    under_reporting: UnderReporting = 'none'
    weather: list[WeatherFilter] | WeatherFilter = Field(
        ['dry', 'rain', 'fog'], title='Weather'
    )
    light_condition: list[LightFilter] | LightFilter = Field(
        'any', title='Light Condition'
    )
    crash_year: list[int] | int = Field([2022], title='Crash Year')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class RouteSelections(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Outcome = 'police_reported'
    severity: int = Field(1, ge=1, le=7, title='Severity')
    ego_vehicle: list[VehicleClass] | VehicleClass = Field(
        ['combination'], title='Ego Vehicle'
    )
    unresolved_nfs: Tier3Mode = 'marginal'
    in_transport: InTransport = 'in_transport'
    weather: list[WeatherFilter] | WeatherFilter = Field(
        ['dry', 'rain', 'fog'], title='Weather'
    )
    light_condition: list[LightFilter] | LightFilter = Field(
        'any', title='Light Condition'
    )
    driver_impairment: DriverImpairment = 'any'
    under_reporting: UnderReporting = 'none'
    ci_method: CiMethod = 'fay_feuer'


class V1BatchItem(BaseModel):
    county: str = Field('travis', title='County')
    selections: GeofenceSelections | None = None


class V1BatchRequest(BaseModel):
    items: list[V1BatchItem] | None = Field(
        None,
        description="One (county, selections) combination per entry. Selections are per-item because a value valid in one county can be invalid in another, so the batch can't share a single selection set.",
        title='Items',
    )
    summary_only: bool = Field(
        True,
        description='Batch defaults to summary-only (no per-cell breakdown), as it exists for multi-county comparison. Set false to include `cells`.',
        title='Summary Only',
    )


class V1ComputeRequest(BaseModel):
    county: str = Field('travis', title='County')
    selections: GeofenceSelections | None = None
    summary_only: bool = Field(
        False,
        description="Drop the per-cell `cells` breakdown (returned as []), keeping just the county-wide scalars. Cuts the bulk of the response for callers that don't need the map heatmap.",
        title='Summary Only',
    )


class V1DepotRequest(BaseModel):
    county: str = Field('travis', title='County')
    depot_a: DepotPin
    depot_b: DepotPin
    selections: DepotSelections | None = None


class V1RouteRequest(BaseModel):
    county: str = Field('travis', title='County')
    segment_ids: list[SegmentId] = Field(
        ...,
        description='Ordered [route, milepost] pairs, e.g. [["I-35", 250], ["I-35", 251]].',
        title='Segment Ids',
    )
    selections: RouteSelections | None = None


class BatchItemResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    county: str = Field(..., title='County')
    result: ComputeResult | None = None
    error: str | None = Field(None, title='Error')


class BatchComputeResult(BaseModel):
    results: list[BatchItemResult] | None = Field(None, title='Results')
